apiVersion: v1 
kind: Secret 
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret 
  namespace: keycloak 
  stringData: 
    POSTGRES_DATABASE: <Database Name> 
    POSTGRES_EXTERNAL_ADDRESS: <External Database IP or URL (resolvable by K8s)> 
    POSTGRES_EXTERNAL_PORT: <External Database Port> # Strongly recommended to use <'Keycloak CR Name'-postgresql> POSTGRES_HOST: <Database Service Name> POSTGRES_PASSWORD: <Database Password> # Required for AWS Backup functionality POSTGRES_SUPERUSER: true POSTGRES_USERNAME: <Database Username> type: Opaque
