apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "sso76-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    application: {{ include "sso76-chart.fullname" . }}
    component: "server"
    rhsso: 7.6.1.GA
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  strategy":
    type: "Recreate"
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers": 
    type": "ImageChange"
    imageChangeParams":
      automatic": true
      containerNames": 
        - "${APPLICATION_NAME}"
      from:
        kind: "ImageStreamTag"
        namespace: openshift
        name: "sso76-openshift-rhel8:7.6"
        type: "ConfigChange"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: {{ include "sso76-chart.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sso76-chart.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: sso-x509-https-volume
          secret:
            secretName: sso-x509-https-secret
            defaultMode: 420
        - name: sso-x509-jgroups-volume
          secret:
            secretName: sso-x509-jgroups-secret
            defaultMode: 420
        - name: service-ca
          configMap:
            name: sso-service-ca
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: sso
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SSO_HOSTNAME
            - name: DB_SERVICE_PREFIX_MAPPING
              value: sso-postgresql=DB
            - name: DB_JNDI
              value: 'java:jboss/datasources/KeycloakDS'
            - name: DB_USERNAME
              value: pgsql
            - name: DB_PASSWORD
              value: pgsql
            - name: DB_DATABASE
              value: root
            - name: TX_DATABASE_PREFIX_MAPPING
              value: sso-postgresql=DB
            - name: DB_MIN_POOL_SIZE
            - name: DB_MAX_POOL_SIZE
            - name: DB_TX_ISOLATION
            - name: JGROUPS_PING_PROTOCOL
              value: openshift.DNS_PING
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: sso-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: X509_CA_BUNDLE
              value: >-
                /var/run/configmaps/service-ca/service-ca.crt
                /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: JGROUPS_CLUSTER_PASSWORD
              value: Y1CO603HRiauQRuYw0IuGrKQIQSO2OsH
            - name: SSO_ADMIN_USERNAME
              value: admin
            - name: SSO_ADMIN_PASSWORD
              value: admin
            - name: SSO_REALM
            - name: SSO_SERVICE_USERNAME
            - name: SSO_SERVICE_PASSWORD
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ping
              containerPort: 8888
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: sso-x509-https-volume
              readOnly: true
              mountPath: /etc/x509/https
            - name: sso-x509-jgroups-volume
              readOnly: true
              mountPath: /etc/x509/jgroups
            - name: service-ca
              readOnly: true
              mountPath: /var/run/configmaps/service-ca
          terminationMessagePolicy: File
          image: openshift/sso76-openshift-rhel8:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

