---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
# now that we deploying using ArgoCD we can specify the order of deploy
  name: {{ include "sso76-chart.fullname" . }}
spec: {}