# OperatorGroup for RHSSO
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
# Sync Wave 1 since we need to have the namespace first
  name: rhsso-dev
  namespace: rhsso-dev
spec:
  targetNamespaces:
  - rhsso-dev
